





AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Description": "AWS CloudFormation Sample Template for creating an Amazon RDS DB instance: 
  Sample template showing how to create a DB instance with Enhanced Monitoring enabled. 
  **WARNING** This template creates an RDS DB instance. You will be billed for the AWS 
  resources used if you create a stack from this template.

Parameters:
  DBInstanceID:
    Default: mydbinstance
    Description: My database instance
    Type: String
    MinLength: '1'
    MaxLength: '63'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: >-
      Must begin with a letter and must not end with a hyphen or contain two
      consecutive hyphens.
  
  DBName:
    Default: AndreDB
    Description: My database created using CloudFormation
    Type: String
    MinLength: '1'
    MaxLength: '64'
    
  
  DBUsernameSSMParameters:
    NoEcho: 'true'
    Description: Username for MySQL database access
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/Andre/rds/Instancetype'
    
  DBPassword:
    NoEcho: 'true'
    Description: Password MySQL database access
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/Andre/rds/Instancetype/password'
    
Resources:
  MyDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceID
      DBName: !Ref DBName
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: postgres
      EngineVersion: "15.7"
      MasterUsername: !Ref DBUsernameSSMParameters
      MasterUserPassword: !Ref DBPassword
      